/*
 *  Copyright 2011 jahziah.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * DownloaderFrame.java
 *
 * Created on Feb 26, 2011, 3:20:28 AM
 */

package net.cheesecan.cheeselobby.ui;

import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;

/**
 *
 * @author jahziah
 */
public class DownloaderFrame extends javax.swing.JFrame {

    /** Creates new form DownloaderFrame */
    public DownloaderFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchGroup = new ButtonGroup();
        dlTabbedPane1 = new JTabbedPane();
        mapScrollPane = new JScrollPane();
        modScrollPane = new JScrollPane();
        widgetScrollPane = new JScrollPane();
        selectedScrollPane = new JScrollPane();
        searchField = new JTextField();
        searchLabel = new JLabel();
        widgetRadioButton = new JRadioButton();
        modRadioButton = new JRadioButton();
        mapRadioButton = new JRadioButton();
        downloadButton = new JButton();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        dlTabbedPane1.addTab("Map", mapScrollPane);
        dlTabbedPane1.addTab("Mod", modScrollPane);
        dlTabbedPane1.addTab("Widget", widgetScrollPane);
        dlTabbedPane1.addTab("Selected", selectedScrollPane);

        searchLabel.setText("Search:");

        searchGroup.add(widgetRadioButton);
        widgetRadioButton.setText("Widget");

        searchGroup.add(modRadioButton);
        modRadioButton.setText("Mod");

        searchGroup.add(mapRadioButton);
        mapRadioButton.setText("Map");

        downloadButton.setText("Download selected");

        jButton1.setText("Clear");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(downloadButton, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(searchField, GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(mapRadioButton)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(modRadioButton)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(widgetRadioButton))
                    .addComponent(dlTabbedPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(searchField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(widgetRadioButton)
                    .addComponent(modRadioButton)
                    .addComponent(mapRadioButton))
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dlTabbedPane1, GroupLayout.PREFERRED_SIZE, 363, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(downloadButton)
                        .addContainerGap())
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloaderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTabbedPane dlTabbedPane1;
    private JButton downloadButton;
    private JButton jButton1;
    private JRadioButton mapRadioButton;
    private JScrollPane mapScrollPane;
    private JRadioButton modRadioButton;
    private JScrollPane modScrollPane;
    private JTextField searchField;
    private ButtonGroup searchGroup;
    private JLabel searchLabel;
    private JScrollPane selectedScrollPane;
    private JRadioButton widgetRadioButton;
    private JScrollPane widgetScrollPane;
    // End of variables declaration//GEN-END:variables

}
